<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Institution.Application\Institution.Application.csproj" />
    <ProjectReference Include="..\Institution.Infrastructure\Institution.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AthenaUnionLibrary">
      <HintPath>..\..\AthenaUnionLibrary\AthenaUnionLibrary\bin\Debug\net10.0\AthenaUnionLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Mediator">
      <HintPath>..\..\AthenaUnionLibrary\Mediator\bin\Debug\net10.0\Mediator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="https://www.schemastore.org/appsscript.json" /></VisualStudio></ProjectExtensions>

</Project>
